[package]

name = "aerospike"
version = "0.0.1"
authors = ["Khosrow Afroozeh <khosrow@aerospike.com>", "Jan Hecking <jhecking@aerospike.com>"]
description = "Aerospike Client for Rust."
keywords = ["aerospike", "nosql", "distributed", "key-value store"]
homepage = "http://www.aerospike.com/"
license = "Apache 2"
readme = "README.md"

[dependencies]
log = "0.3"
byteorder = "^0.5"
rust-crypto = "^0.2"
rustc-serialize = "0.3"
crossbeam = "0.2"
rand = "0.3"
threadpool = "1.0"
pwhash = "0.1"
lazy_static = "^0.2"

[dev-dependencies]
env_logger = "0.3"
hex = "^0.2"

#[profile.release]
#debug = true
